### ISSUE TITLE
目前只支持每日签到了吗

### ISSUE THREAD

**Issue by xsdeath** [Chenghow/youthstudy-tool#11]
rt

**Comment by huoyiming** [comment]
经测试 没刷过积分的mid可以正常使用，暂不清楚具体原因，可能是触发系统阈值

**Comment by Chenghow** [comment]
团课学习打卡与每日签到与均可正常使用，目前不知其它功能失效的原因

**Comment by Chenghow** [comment]
另外，学习频道的资源未更新自然不会增加积分

**Comment by Chenghow** [comment]
“学习频道”已答过或学习过无法再加积分，学习频道一日积分仅可加20分，当到达这个阈值时，程序接下来的请求便不会增加积分。目前通过[提高pageSize以获得全部元素](https://github.com/Chenghow/youthstudy-tool/commit/dc0bae8858ce6f981cfc016a1180b560d5bb4961)，[[feat] 达到每日积分限制自动跳过](https://github.com/Chenghow/youthstudy-tool/commit/afcb87debc44212bf81710fa8b887d51fc139ed0)两个手段达到获取全部可学习项目并在达到阈值时停下来 。
