### ISSUE TITLE
希望可以增加企业微信推送

### ISSUE THREAD

**Issue by NianBroken** [Chenghow/youthstudy-tool#16]
例如：
![image](https://user-images.githubusercontent.com/57057288/193439030-ed10e6b8-409f-456f-8960-270f54f268af.png)

**Comment by huoyiming** [comment]
没接触过企业微信，能够提供demo或api文档的话或许可以考虑

**Comment by huoyiming** [comment]
> > 没接触过企业微信，能够提供demo或api文档的话或许可以考虑
> 
> 使用企业微信推送的库：https://github.com/chen310/NeteaseCloudMusicTasks Api：https://developer.work.weixin.qq.com/document

看了一下，和现有推送有较大差异（不支持html）而且步骤比较繁琐，暂不考虑（当然也欢迎pr）
