### ISSUE TITLE
需求：只有青年大学习更新时，才进行推送。

### ISSUE THREAD

**Issue by NianBroken** [Chenghow/youthstudy-tool#23]
只有更新了青年大学习时，才进行推送
如：
名称："青年大学习"2024年第1期
打卡状态：成功

未更新青年大学习时，则不推送
如：
名称："青年大学习"2024年第1期
打卡状态：当期已学习，自动跳过

**Comment by huoyiming** [comment]
功能已大致实现，如何使用请查阅：https://github.com/Chenghow/youthstudy-tool/blob/master/README.md?plain=1#L34
