### ISSUE TITLE
关于“finishpage.dgstu.tk”接口，能否加上评分的五角星？

### ISSUE THREAD

**Issue by NianBroken** [Chenghow/youthstudy-tool#27]
在最新的青年大学习官方完成页中存在评分的五角星，但“finishpage.dgstu.tk”接口没有。

**Comment by huoyiming** [comment]
加上了，考虑到只是截图用，就做成纯静态了

**Comment by huoyiming** [comment]
补充一句：“finishpage.dgstu.tk”没有接口，纯前端的一个html，源码直接ctrl+U可以看到，有需要的话可以自行部署
